version: 0.2

phases:
 install:
   runtime-versions:
       nodejs: 12
   commands:
     - echo "Installing Gatsby..."
     - npm install -g gatsby-cli
 pre_build:
   commands:
     - echo "Installing Node packages..."
     - npm install
 build:
   commands:
     - echo "Build initiated..."
     - gatsby build
 post_build:
   commands:
     - echo "Synchronizing public directory..."
     - aws s3 sync ./public/ s3://$PUBLIC_OUTPUT_BUCKET --delete

artifacts:
 base-directory: public
 files:
   - '**/*'
